# Generated by Django 3.1.3 on 2021-11-20 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_question_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
    ]
